services:
  bot:
    build: .
    container_name: vistly_bot
    restart: unless-stopped
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      ADMINS: ${ADMINS}
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${POSTGRES_USER}      # ← Из postgres/.env
      DB_PASS: ${POSTGRES_PASSWORD}  # ← Из postgres/.env
      OMDB_API_KEY: ${OMDB_API_KEY}
      KP_API_KEY: ${KP_API_KEY}
    networks:
      - infra

networks:
  infra:
    external: true