STRINGS = {
    "en": {
        "lang_choose": "Выберите язык / Choose language:",
        "start_message": "Hi! Enter the name of the movie or TV series to search for:",
        "help_message": "Help message",
        "profile": "Profile",
        "restart": "Reset",
        "list": "My list",
        "global": "Global search",
        "local": "My list search",
        "search_choose_question": "Choose search type:",
        "message_error": "Invalid input. Use /restart to restart the bot",
        "searching_please_wait": "Searching please wait...",
        "nothing_found_query": "Nothing was found for the query: <b>{query}</b>",
        "found_results": "Found {total_results} for: <b>{query}</b>",
        "feature_developing": "Feature is developing",
        "page_of_total_pages": "{page} of {total_pages}",
        "change_entity_type": "Filter",
        "cancel": "Cancel",
        "back": "Back",
        "in_progress": "In progress",
        "completed": "Completed",
        "planning": "Planning",
        "add_to_list": "Save",
        "select_status_type_for": "Select status type for <b>{entity_name}</b>",
        "entity_added_to_list": "<b>{entity_title}</b> has been successfully added with <b>{status_type}</b> status",
        "user_list_empty": "Your list is empty",
        "user_list_empty_status": "No {status} items in your list",
        "rating": "Rating",
        "runtime": "Runtime",
        "seasons": "Seasons",
        "genre": "Genre",
        "country": "Country",
        "director": "Director",
        "actors": "Actors",
        "movie": "Movie",
        "series": "Series",
        "game": "Game",
        "book": "Book",
        "mixed": "Mixed",
        "undefined": "Undefined",
        "all": "All",
        "set_rating": "Set rating",
        "user_rating": "Rating: {rating}",
        "set_season": "Set season",
        "user_season": "Season: {season}",
        "set_status": "Set status",
        "user_status": " {status}",
        "delete": "Delete",
        "share": "Share",
        "yes": "Yes",
        "no": "No",
        "clean": "Clean",
        "ask_rating": "Please rate {entity_type} {entity_name}",
        "ask_season": "Please set season for {entity_type} {entity_name}",
        "ask_status": "Please set status for {entity_type} {entity_name}",
        "ask_delete": "Are you sure you want to delete {entity_type} {entity_name}?",
        "entity_deleted": "Entity deleted from your list.",
        "user_list_title": "You have <b>{total_results}</b> with <b>{status_text}</b> items:",
        "confirm": "Confirm",
        "already_added": "Already added",
        "unknown_command": "Unknown command. Use /help for help.",
        "min": "min",
    },
    "ru": {
        "lang_choose": "Выберите язык / Choose language:",
        "start_message": "Привет! Просто введи название фильма или сериала для поиска:",
        "help_message": "Помощь",
        "profile": "Профиль",
        "restart": "Сброс",
        "list": "Мой список",
        "global": "Глобальный поиск",
        "local": "В моем списке",
        "search_choose_question": "Выберите тип поиска:",
        "message_error": "Неверный ввод. Используйте /restart для перезапуска бота",
        "searching_please_wait": "Поиск... Пожалуйста, подождите...",
        "nothing_found_query": "Ничего не найдено для запроса: <b>{query}</b>",
        "found_results": "Найдено {total_results} по запросу: <b>{query}</b>",
        "feature_developing": "Функция в разработке",
        "page_of_total_pages": "{page} из {total_pages}",
        "change_entity_type": "Фильтрация",
        "cancel": "Отмена",
        "back": "Назад",
        "in_progress": "Смотрю",
        "completed": "Посмотрел",
        "planning": "Хочу",
        "add_to_list": "Сохранить",
        "select_status_type_for": "Выберите статус для <b>{entity_name}</b>",
        "entity_added_to_list": "<b>{entity_title}</b> успешно добавлен в ваш список с статусом <b>{status_type}</b>",
        "user_list_empty": "Ваш список пуст",
        "user_list_empty_status": "Нет объектов со статусом {status} в вашем списке",
        "rating": "Рейтинг",
        "runtime": "Продолжительность",
        "seasons": "Сезоны",
        "genre": "Жанр",
        "country": "Страна",
        "director": "Режиссёр",
        "actors": "Актеры",
        "movie": "Фильм",
        "series": "Сериал",
        "game": "Игра",
        "book": "Книга",
        "mixed": "Смешанный",
        "undefined": "Неопределенный",
        "all": "Все",
        "set_rating": "Оценить",
        "user_rating": "Оценка {rating}",
        "set_season": "Сезон",
        "user_season": "Сезон {season}",
        "set_status": "Статус",
        "user_status": "{status}",
        "delete": "Удалить",
        "share": "Поделиться",
        "yes": "Да",
        "no": "Нет",
        "clean": "Очистить",
        "ask_rating": "Пожалуйста, оцените {entity_type} {entity_name}",
        "ask_season": "Пожалуйста, установите сезон для {entity_type} {entity_name}",
        "ask_status": "Пожалуйста, установите статус для {entity_type} {entity_name}",
        "ask_delete": "Вы уверены, что хотите удалить {entity_type} {entity_name}?",
        "entity_deleted": "Объект удален из вашего списка.",
        "user_list_title": "У вас <b>{total_results}</b> объектов со статусом <b>{status_text}</b>:",
        "confirm": "Подтвердить",
        "already_added": "Уже добавлено",
        "unknown_command": "Неизвестная команда. Используйте /help для получения помощи.",
        "min": "мин",
    },
}

STATUS_STRINGS = {
    "en": {
        "in_progress": "In progress",
        "completed": "Completed",
        "planning": "Planning",
    },
    "ru": {
        "in_progress": "Смотрю",
        "completed": "Посмотрел",
        "planning": "Хочу",
    },
}


def get_string(key, lang="en") -> str:
    return STRINGS.get(lang, STRINGS["en"]).get(key, key)


def get_status_string(status: str, lang: str = "en") -> str:
    return STATUS_STRINGS.get(lang, STATUS_STRINGS["en"]).get(status, status)
